package intentioncloud::Schema;

use strict;
use base qw/DBIx::Class::Schema::Loader/;

__PACKAGE__->loader_options(
    relationships => 1,
    # debug => 1,
);

=head1 NAME

intentioncloud::Schema - DBIx::Class::Schema::Loader class

=head1 SYNOPSIS

See L<intentioncloud>

=head1 DESCRIPTION

Generated by L<Catalyst::Model::DBIC::Schema> for use in L<intentioncloud::Model::DB>

=head1 AUTHOR

franck cuny,,,

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;

